### PR TITLE
appveyor and x64

### PR DESCRIPTION
**Pull request by chcg**
- config appveyor.yml CI
- x64 build target (excluded vsextension which is not available from the standard appveyor vm installation)

, see https://ci.appveyor.com/project/chcg/js-map-parser/build/4.1.7

JSparser.sln could be reduced to just x64 + any cpu and strip away Mixed Platforms, x86, I think.

### CODE REVIEW

**Comment by chcg** [comment]
@megaboich Any chance to get this reviewed/merged? Or may I create a forked release for the N++ x64 plugin?

**Comment by megaboich** [comment]
Hi @chcg 
As I see you have some interest in this project.
Unfortunately I do not have possibility to continue its maintenance, because I have somehow ended up as migrated out of Microsoft, .Net and Windows ecosystems. 
So if you wish I can transfer this repository to you and you can maintain it further, or I can just add you as a collaborator.

**Comment by chcg** [comment]
@megaboich Adding as a collaborator is fine for me as you are still available and maybe I could get back on you for some general questions.

**Comment by megaboich** [comment]
@chcg Sure, I am still available around, but unfortunately I do not have Visual Studio at my hands :(
I have created request to add you as a collaborator.

**Pull request merged**
